spring:
  application:
    name: analytics-processor-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: analytics-processor-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8083

  elasticsearch:
    uris: http://localhost:9200
