spring:
  application:
    name: analytics-query-service
  elasticsearch:
    uris: http://localhost:9200

server:
  port: 8084

jwt:
  secret: Q9pX7mL2aF8CwZsYB6JdK4E3N5V0R1UO
  access-token-expiration: 86400000      # 15 minutes
  refresh-token-expiration: 604800000  # 7 days
